apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: PUT-HERE-YOUR-MINIKUBE-IP:5000/hello-world-rust:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
         requests:
          memory: "16Mi"
          cpu: "62.5m"
         limits:
          memory: "32Mi"
          cpu: "62.5m"
