apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-world-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-world-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30

